"""Application-facing network interface."""
from typing import Protocol

from client.contracts.messages import NetworkEvent, NetworkRequest


class NetworkPort(Protocol):
    def start(self) -> None: ...
    def submit(self, request: NetworkRequest) -> bool: ...
    def drain_events(self, limit: int = 200) -> list[NetworkEvent]: ...
    def is_alive(self) -> bool: ...
    def stop(self, timeout: float | None = None) -> None: ...
